apiVersion: v1
kind: ConfigMap
metadata:
  name: dashboard-config
data:
  settings.yaml: |
    title: Homelab Dashboard
    favicon: https://github.com/walkxcode/dashboard-icons/blob/main/png/heimdall.png?raw=true
    headerStyle: boxed
    layout:
      Services:
        style: row
        columns: 2

  services.yaml: |
    - Services:
        - Golf:
            href: https://walkerrout.ca
            description: Portfolio website
            icon: mdi-golf
        - Counter:
            href: https://counter.walkerrout.ca
            description: Poker tracker
            icon: mdi-counter

#  bookmarks.yaml: |
#    - Developer:
#        - GitHub:
#            - abbr: GH
#              href: https://github.com

#  widgets.yaml: |
#    - search:
#        provider: google
#        target: _blank
